[build]
  # Wir geben uns mit 'ls' genau aus, was erzeugt wurde, um den Fehler zu finden
  command = "pnpm install && pnpm --filter playground run build && ls -R playground/.output"
  publish = "playground/.output/public"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--shamefully-hoist"
