[build]
  # Netlify wechselt automatisch in diesen Ordner
  base = "playground"
  # Befehl wird RELATIV zum base-ordner ausgef√ºhrt
  command = "pnpm run build"
  # Pfad RELATIV zum base-ordner
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
